In [1]:
import tensorflow as tf
import numpy as np

# XOR Dataset

In [4]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)


# XOR with logistic regression
## not work

Hypothesis:  [[ 0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]] 
Correct:  [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] 
Accuracy:  0.5

In [6]:

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 1.13372 [[-0.17356631]
 [-1.45647013]]
100 0.702247 [[ 0.28494906]
 [-0.4550595 ]]
200 0.695745 [[ 0.15242901]
 [-0.2445226 ]]
300 0.693915 [[ 0.07526305]
 [-0.13704604]]
400 0.693377 [[ 0.03587813]
 [-0.07757889]]
500 0.693218 [[ 0.01623418]
 [-0.04438196]]
600 0.69317 [[ 0.00669189]
 [-0.02569094]]
700 0.693155 [[ 0.00223786]
 [-0.01506159]]
800 0.69315 [[ 0.00029302]
 [-0.00894859]]
900 0.693148 [[-0.00045262]
 [-0.0053896 ]]
1000 0.693148 [[-0.00065295]
 [-0.00329035]]
1100 0.693147 [[-0.00062633]
 [-0.00203526]]
1200 0.693147 [[-0.00052192]
 [-0.00127457]]
1300 0.693147 [[-0.00040525]
 [-0.00080734]]
1400 0.693147 [[-0.00030183]
 [-0.00051664]]
1500 0.693147 [[-0.00021888]
 [-0.00033362]]
1600 0.693147 [[-0.00015582]
 [-0.00021711]]
1700 0.693147 [[-0.00010948]
 [-0.00014223]]
1800 0.693147 [[ -7.61974152e-05]
 [ -9.36869255e-05]]
1900 0.693147 [[ -5.26550648e-05]
 [ -6.19951461e-05]]
2000 0.693147 [[ -3.61952443e-05]
 [ -4.11797264e-05]]
2100 0.693147 [[ -2.47764874e-05]
 [ -2.

# Neural Network

Hypothesis:  
[[ 0.01890219]
 [ 0.98528594]
 [ 0.98526824]
 [ 0.01621521]] 
 
Correct:  
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
 
Accuracy:  1.0

In [8]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)


0 0.71113 [array([[ 1.25740612, -0.03895469],
       [ 1.27335155,  0.2913284 ]], dtype=float32), array([[-0.44715703],
       [ 0.02830711]], dtype=float32)]
100 0.696488 [array([[ 1.22682905, -0.03797392],
       [ 1.24341691,  0.29228523]], dtype=float32), array([[-0.20387402],
       [ 0.07473169]], dtype=float32)]
200 0.694791 [array([[ 1.21197104, -0.03831981],
       [ 1.22889113,  0.29193404]], dtype=float32), array([[-0.10025603],
       [ 0.04171564]], dtype=float32)]
300 0.693245 [array([[ 1.20704377, -0.03852906],
       [ 1.22406709,  0.29173312]], dtype=float32), array([[-0.00075564],
       [ 0.00893717]], dtype=float32)]
400 0.691758 [array([[ 1.21163285, -0.03844625],
       [ 1.2285713 ,  0.29180938]], dtype=float32), array([[ 0.096949  ],
       [-0.02352151]], dtype=float32)]
500 0.690254 [array([[ 1.22553062, -0.03792256],
       [ 1.24224019,  0.29228795]], dtype=float32), array([[ 0.19410136],
       [-0.05610808]], dtype=float32)]
600 0.68866 [array([[ 1.2486833

## Wide NN for XOR

In [9]:
W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

Hypothesis:  
[[ 0.00514362]
 [ 0.99136752]
 [ 0.99205703]
 [ 0.01066235]] 
 
Correct:  
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
 
Accuracy:  1.0

In [10]:

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            # run W1 W2  <<<<<<<-----------------------------------------------------------------
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                      feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.81221 [array([[ 1.03634143,  2.49793077, -2.28267288,  1.44477522, -0.4177528 ,
         0.14854105, -0.97315818, -1.56965184, -1.8991996 ,  0.61514497],
       [-0.45308357,  1.23613334,  0.81743509, -1.10489213,  0.29169875,
         0.25254342,  0.93549168,  0.5642584 , -0.55041522, -0.11243666]], dtype=float32), array([[-1.0409981 ],
       [ 0.55515677],
       [ 1.05620658],
       [-0.78706729],
       [ 0.00259469],
       [ 0.26803297],
       [ 0.26474893],
       [-1.26622009],
       [ 0.53299302],
       [-0.82540905]], dtype=float32)]
100 0.68589 [array([[ 0.99817443,  2.56554794, -2.27878428,  1.51382005, -0.42450634,
         0.16235244, -0.96721989, -1.54002011, -1.86693728,  0.57719928],
       [-0.34684217,  1.33231115,  0.64226615, -1.04244208,  0.29915094,
         0.23779808,  0.92932898,  0.44531897, -0.50861132, -0.09329523]], dtype=float32), array([[-1.00797832],
       [ 0.81226403],
       [ 0.65246254],
       [-0.80410492],
       [-0.13411689],
       

## Deep NN for XOR

In [12]:
W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([10, 1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')
hypothesis = tf.sigmoid(tf.matmul(layer3, W4) + b4)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            # run W1 W2  <<<<<<<-----------------------------------------------------------------
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run([W1, W2,W3,W4]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                      feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.697001 [array([[-0.14129063, -0.1771789 ,  0.48490715, -1.08177531,  0.51919812,
         0.13647288,  1.58251595, -0.16893211, -1.02968991,  0.09811924],
       [-2.07824612,  1.45460641, -0.00376403, -0.03095256, -0.39444897,
         0.66325939,  0.23471893, -0.35257626,  1.99884474, -1.93974495]], dtype=float32), array([[-0.88971758, -0.0846747 ,  0.0766324 ,  0.54679394,  0.76399493,
        -1.16049111, -1.15400982, -1.80770576,  0.27376032,  2.07808661],
       [ 1.00645053, -0.73774946,  1.14659703, -1.09624732,  2.22535276,
         1.8226335 ,  0.06730869,  2.62938523, -0.4535794 , -1.20641804],
       [-1.99807906, -1.5187552 ,  0.02031828, -1.01280344, -0.11543908,
         0.14572409, -2.14052439, -0.87986255, -2.36377788,  0.35007912],
       [-0.90594774, -0.401297  ,  1.17424178, -0.11698737,  0.28478953,
         0.052641  ,  1.64623094,  0.3151097 ,  1.46643293, -0.22250345],
       [-0.29560408, -0.62799215,  1.45819974,  0.97340578, -1.58080184,
         0.34730