# pp Pretty print

In [19]:
import pprint as pp
pp.pprint(t)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])


# Simple 1D array and slicing

In [12]:
import numpy as np
import pprint as pp
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)
pp.pprint(t)

[ 0.  1.  2.  3.  4.  5.  6.]
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])


In [13]:
print(t.ndim)  #rank or Number of array dimensions.

1


In [15]:
print(t.shape)

(7,)


In [16]:
print(t[0],t[1],t[-1])

0.0 1.0 6.0


In [17]:
print(t[2:5],t[4:-1])

[ 2.  3.  4.] [ 4.  5.]


In [18]:
print(t[:2],t[3:])

[ 0.  1.] [ 3.  4.  5.  6.]


# 2D Array

In [21]:
m = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])

In [23]:
pp.pprint(m)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])


In [25]:
print(m.ndim)

2


In [27]:
print(m.shape)

(4, 3)


# Shape rank Axis

In [34]:
import tensorflow as tf
sess = tf.Session()
n = tf.constant([1,2,3,4])

In [50]:
sess.run(tf.shape(n))

array([4], dtype=int32)

In [53]:
matrix1 = tf.constant([[1.,2.],[3.,4.]])
matrix2 = tf.constant([[1.],[2.]])

print("Metrix1 shape",matrix1.shape)
print("Metrix2 shape",matrix2.shape)
sess.run(tf.matmul(matrix1,matrix2))


Metrix1 shape (2, 2)
Metrix2 shape (2, 1)


array([[  5.],
       [ 11.]], dtype=float32)

In [54]:
sess.run(matrix1*matrix2)

array([[ 1.,  2.],
       [ 6.,  8.]], dtype=float32)

# Broadcasting

In [48]:
# operations between the same shapes
matrix3 = tf.constant([[3.,3.]])
matrix4 = tf.constant([[2.,3.]])

sess.run(matrix3+matrix4)

array([[ 5.,  6.]], dtype=float32)

In [55]:
# operations between the same shapes
matrix5 = tf.constant([[1.,2.]])
matrix6 = tf.constant([[3.]])

sess.run(matrix5+matrix6)

array([[ 4.,  5.]], dtype=float32)

In [56]:
# operations between the same shapes
matrix7 = tf.constant([[1.,2.]])
matrix8 = tf.constant([[3.,4.]])

sess.run(matrix7+matrix8)

array([[ 4.,  6.]], dtype=float32)

In [57]:
# operations between the same shapes
matrix71 = tf.constant([[1.,2.]])
matrix82 = tf.constant([[3.],[4.]])

sess.run(matrix71+matrix82)

array([[ 4.,  5.],
       [ 5.,  6.]], dtype=float32)

# reduce_mean

In [59]:
sess.run(tf.reduce_mean([1,2],axis=0))

1

In [61]:
sess.run(tf.reduce_mean([1.,2.],axis=0))

1.5

In [60]:
x = [[1.,2.],[3.,4.]]
sess.run(tf.reduce_mean(x))

2.5

In [62]:
sess.run(tf.reduce_mean(x,axis=0))

array([ 2.,  3.], dtype=float32)

In [63]:
sess.run(tf.reduce_mean(x,axis=1))

array([ 1.5,  3.5], dtype=float32)

In [64]:
sess.run(tf.reduce_mean(x,axis=-1))

array([ 1.5,  3.5], dtype=float32)

# reduce_sum

In [65]:
x1 = [[1.,2.],[3.,4.]]

In [66]:
sess.run(tf.reduce_sum(x1))

10.0

In [67]:
sess.run(tf.reduce_sum(x1,axis=0))

array([ 4.,  6.], dtype=float32)

In [68]:
sess.run(tf.reduce_sum(x1,axis=1))

array([ 3.,  7.], dtype=float32)

In [69]:
sess.run(tf.reduce_mean(tf.reduce_sum(x1,axis=-1)))

5.0

In [70]:
sess.run(tf.reduce_mean(tf.reduce_sum(x1,axis=0)))

5.0

# arg_max

In [71]:
x2 = [[0,1,2],[2,1,0]]

In [79]:
sess.run(tf.arg_max(x2,0))
# sess.run(tf.arg_max(x2))  # required positional argument: 'dimension'
# sess.run(tf.arg_max(x2,axis= 0))

array([1, 0, 0])

In [77]:
sess.run(tf.arg_max(x2,1))

array([2, 0])

In [80]:
sess.run(tf.arg_max(x2,-1))

array([2, 0])

# reshape

In [81]:
r = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])

In [87]:
r.shape


(2, 2, 3)

In [88]:
pp.pprint(r)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [91]:
print(tf.reshape(r, shape=[-1,3]))

Tensor("Reshape_7:0", shape=(4, 3), dtype=int64)


In [94]:
u = tf.reshape(r, shape=[-1,3])
print(u)

Tensor("Reshape_10:0", shape=(4, 3), dtype=int64)


In [96]:
pp.pprint(u)

<tf.Tensor 'Reshape_10:0' shape=(4, 3) dtype=int64>


In [97]:
sess.run(u)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [93]:
sess.run(tf.reshape(r, shape=[-1,3]))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [99]:
pp.pprint(r)   # not change the shape of matrix

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [101]:
sess.run(tf.reshape(r, shape=[-1,1,3]))

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [102]:
sess.run(tf.reshape(r, shape=[-1,1,2,3]))

array([[[[ 0,  1,  2],
         [ 3,  4,  5]]],


       [[[ 6,  7,  8],
         [ 9, 10, 11]]]])

# reshape
## squeeze expand

In [103]:
sess.run(tf.squeeze([[1],[2],[3]]))

array([1, 2, 3], dtype=int32)

In [110]:
sess.run(tf.expand_dims([1, 2, 3, 4],1))
# sess.run(tf.expand_dims([1, 2, 3, 4],4)) not work

array([[1],
       [2],
       [3],
       [4]], dtype=int32)

# one-hot

In [121]:
one_hot =tf.one_hot([[0],[1],[2],[0]],depth=3)

In [120]:
 sess.run(tf.one_hot([[0],[1],[2],[0]],depth=3))

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [118]:
sess.run(tf.one_hot([[0],[1],[2],[0]],depth=4))

array([[[ 1.,  0.,  0.,  0.]],

       [[ 0.,  1.,  0.,  0.]],

       [[ 0.,  0.,  1.,  0.]],

       [[ 1.,  0.,  0.,  0.]]], dtype=float32)

In [122]:
sess.run(tf.reshape(one_hot,shape=[-1,3]))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

# Casting

In [123]:
tf.cast([1.8,2.2,3.3,4.9],tf.int32)

<tf.Tensor 'Cast:0' shape=(4,) dtype=int32>

In [124]:
sess.run(tf.cast([1.8,2.2,3.3,4.9],tf.int32))

array([1, 2, 3, 4], dtype=int32)

In [125]:
sess.run(tf.cast([True, False, 1==1, 0==1],tf.int32))

array([1, 0, 1, 0], dtype=int32)

# Stack

In [126]:
ax = [1,4]
by = [2,5]
cz = [3,6]

In [127]:
# Pack along first dim
sess.run(tf.stack([ax,by,cz]))

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [128]:
sess.run(tf.stack([ax,by,cz],axis=1))

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [129]:
sess.run(tf.stack([by,ax,cz]))

array([[2, 5],
       [1, 4],
       [3, 6]], dtype=int32)

# ones and zeros like

In [133]:
xp = [[0,1,2],[2,1,0]]
print(xp)
pp.pprint(xp)

[[0, 1, 2], [2, 1, 0]]
[[0, 1, 2], [2, 1, 0]]


In [131]:
sess.run(tf.ones_like(xp))

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [134]:
sess.run(tf.zeros_like(xp))

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

# zip

In [135]:
for x,y in zip([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [137]:
for x,y,z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
