In [8]:
import tensorflow as tf
import numpy as np

# training and test dataset

In [9]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], 
          [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], 
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]


In [11]:
X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])

W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean( -tf.reduce_sum(Y * tf.log(hypothesis),axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)



# Correct prediction Test model

## arg_max function

arg_max(
    input,
    dimension,
    name=None
)

Returns the index with the largest value across dimensions of a tensor.
返回在张量的尺寸上具有最大值的索引

# correct_prediction = tf.equal(tf.arg_max(hypothesis,1),tf.arg_max(Y,1))
Returns the index with the largest value across axes of a tensor.
for we use 'softmax_cross_entropy_with_logits',
the prediction are presented as the paobability
by the argmax function we will get the index of largest probability of prediction
but why we need use tf.arg_max(Y,1)?

In [12]:

prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction,tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))


In [17]:
# launch graph
with tf.Session() as sess:   # error Session()
    # Initialize Tensorflow Variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X:x_data,Y:y_data})
        if step % 20 == 0:
            print("step: ", step, "cost_val: ", cost_val, "\n", W_val)
    
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict= {X: x_test}))
    # Calculate the accuracy
    print("Accurancy: ", sess.run(accuracy, feed_dict= {X:x_test, Y: y_test}))

step:  0 cost_val:  7.31662 
 [[-0.68406874  0.75542504 -0.80705446]
 [-0.10571302  0.65812552 -0.59445602]
 [-1.14200139 -2.67441535  0.82745177]]
step:  20 cost_val:  1.32021 
 [[-0.68334168  0.6520744  -0.70443094]
 [ 0.23146959  0.58123231 -0.85474533]
 [-0.74565381 -1.78859437 -0.45471665]]
step:  40 cost_val:  0.903405 
 [[-0.75569719  0.49936181 -0.47936308]
 [ 0.19915093  0.22402082 -0.46521506]
 [-0.70933485 -1.3648262  -0.9148035 ]]
step:  60 cost_val:  0.734453 
 [[-0.83102334  0.38582042 -0.2904956 ]
 [ 0.17799838  0.03061639 -0.25065795]
 [-0.66760868 -1.12296295 -1.19839287]]
step:  80 cost_val:  0.668113 
 [[-0.90378022  0.30077133 -0.13268957]
 [ 0.16146839 -0.04716113 -0.15635048]
 [-0.62252873 -1.00698638 -1.35944963]]
step:  100 cost_val:  0.631634 
 [[-0.97408336  0.23513389  0.00325097]
 [ 0.14818582 -0.07318466 -0.11704438]
 [-0.57976276 -0.95025533 -1.45894647]]
step:  120 cost_val:  0.606179 
 [[-1.04265654  0.18360801  0.12335014]
 [ 0.13864879 -0.07832248 -0.1

# Learning Rate
###### Large learning rate : Overshooting
###### Small learning rate : Many iterations until covergence and trapping in local minima

### try to change the learning rate at 1.5 or 1e-10






# Nomalized inputs vs Non-N

In [24]:
# non_normalized inputs

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
              [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
              [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
              [816, 820.958984, 1008100, 815.48999, 819.23999],
              [819.359985, 823, 1188100, 818.469971, 818.97998],
              [819, 823, 1198100, 816, 820.450012],
              [811.700012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# Normalize the inputs xy

In [27]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [28]:
xy = MinMaxScaler(xy)
print(xy)

[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]


In [30]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
       [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 500 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  6.10542 
Prediction:
 [[-3.42465353]
 [-2.46258831]
 [-1.901227  ]
 [-1.28815567]
 [-1.72189927]
 [-1.49801779]
 [-0.31831166]
 [ 0.00527349]]
500 Cost:  5.89861 
Prediction:
 [[-3.36354065]
 [-2.40538287]
 [-1.85370564]
 [-1.25157619]
 [-1.67820227]
 [-1.45596313]
 [-0.29142073]
 [ 0.03104682]]
1000 Cost:  5.69947 
Prediction:
 [[-3.30354261]
 [-2.34925771]
 [-1.80708539]
 [-1.21569622]
 [-1.6353327 ]
 [-1.4147079 ]
 [-0.26506683]
 [ 0.05629282]]
1500 Cost:  5.50775 
Prediction:
 [[-3.24464226]
 [-2.2941947 ]
 [-1.76135159]
 [-1.18050325]
 [-1.59327638]
 [-1.37423837]
 [-0.23923969]
 [ 0.08102126]]
2000 Cost:  5.32313 
Prediction:
 [[-3.18681335]
 [-2.24017048]
 [-1.71648443]
 [-1.14598298]
 [-1.5520159 ]
 [-1.33453739]
 [-0.2139293 ]
 [ 0.10524245]]
