In [30]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

In [31]:
xy = np.loadtxt('data.csv',delimiter=',',dtype=np.float32)

In [32]:
x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]  ##### error

print(x_data.shape,'\n', x_data,'\n',len(x_data))
print(y_data.shape,'\n', y_data,'\n',len(y_data))


(25, 3) 
 [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 
 25
(25, 1) 
 [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]] 
 25


In [33]:
# placehiolders for a tensor that will be always fed
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name="weight")
b = tf.Variable(tf.random_normal([1]),name="bias")

# Hypothsis 
hypothsis = tf.matmul(X,W)+b
# simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothsis - Y))

# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


In [ ]:
# Launch the graph in a Session
sess = tf.Session()
# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val,hy_val,_ = sess.run([cost,hypothsis,train],
                feed_dict= {X:x_data,Y:y_data})
    if step%10==0:
        print(step,"Cost:",sess.run(tf.transpose(cost_val)),"\nPrediction:\n",hy_val)
# Ask my Score        
print("your score will be",
      sess.run(hypothsis,feed_dict={X:[[100,70,101]]}))
print("other scores will be",
     sess.run(hypothsis,feed_dict={X:[[60,70,100],[90,100,80]]}))

0 Cost: 51995.9 
Prediction:
 [[-51.69717789]
 [-77.80619049]
 [-68.30496216]
 [-76.40849304]
 [-61.82901764]
 [-51.04413986]
 [-56.19522095]
 [-39.67947388]
 [-79.08525085]
 [-79.46579742]
 [-56.74660492]
 [-63.80874634]
 [-68.63928223]
 [-55.30405807]
 [-59.06064606]
 [-79.49099731]
 [-55.08837891]
 [-64.84874725]
 [-62.7055397 ]
 [-54.89693069]
 [-67.21638489]
 [-74.12146759]
 [-62.18757248]
 [-47.61909866]
 [-77.09774017]]
10 Cost: 81.1191 
Prediction:
 [[ 161.01931763]
 [ 177.92729187]
 [ 183.63710022]
 [ 197.99163818]
 [ 133.21299744]
 [  92.78516388]
 [ 149.20782471]
 [ 112.59871674]
 [ 159.95132446]
 [ 141.98188782]
 [ 141.15228271]
 [ 131.35983276]
 [ 191.63641357]
 [ 161.04281616]
 [ 147.2984314 ]
 [ 180.02740479]
 [ 150.95509338]
 [ 181.64938354]
 [ 185.417099  ]
 [ 167.10929871]
 [ 173.65525818]
 [ 165.80220032]
 [ 167.45422363]
 [ 166.81401062]
 [ 187.92221069]]
20 Cost: 78.0091 
Prediction:
 [[ 162.44917297]
 [ 179.71304321]
 [ 185.36065674]
 [ 199.88499451]
 [ 134.578216

In [1]:
import tensorflow as tf

In [5]:
import numpy as np
import time
 
start = time.clock()

tf.set_random_seed(777) # for reproducibility
xy = np.loadtxt('data.csv',delimiter=',',dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]  ##### error

# placehiolders for a tensor that will be always fed
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name="weight")
b = tf.Variable(tf.random_normal([1]),name="bias")

# Hypothsis 
hypothsis = tf.matmul(X,W)+b
# simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothsis - Y))

# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a Session
sess = tf.Session()
# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val,hy_val,_ = sess.run([cost,hypothsis,train],
                feed_dict= {X:x_data,Y:y_data})
    if step%10==0:
        print(step,"Cost:",sess.run(tf.transpose(cost_val)),"\nPrediction:\n",hy_val)
# Ask my Score        
print("your score will be",
      sess.run(hypothsis,feed_dict={X:[[100,70,101]]}))
print("other scores will be",
     sess.run(hypothsis,feed_dict={X:[[60,70,100],[90,100,80]]}))

elapsed = (time.clock() - start)
print("Time used:",elapsed)

0 Cost: 150936.0 
Prediction:
 [[-219.18812561]
 [-248.11853027]
 [-252.43920898]
 [-273.94216919]
 [-186.26420593]
 [-134.08129883]
 [-207.94458008]
 [-158.63516235]
 [-227.16192627]
 [-206.90811157]
 [-196.78434753]
 [-186.91488647]
 [-261.51202393]
 [-217.76171875]
 [-206.50784302]
 [-252.27235413]
 [-203.82183838]
 [-252.46022034]
 [-251.83030701]
 [-226.82421875]
 [-241.97140503]
 [-232.81503296]
 [-232.2792511 ]
 [-222.7538147 ]
 [-259.99185181]]
10 Cost: 49.2049 
Prediction:
 [[ 143.54934692]
 [ 187.81489563]
 [ 177.11569214]
 [ 193.87384033]
 [ 146.19677734]
 [ 111.02064514]
 [ 142.24151611]
 [ 100.98600769]
 [ 180.23648071]
 [ 170.43386841]
 [ 140.59077454]
 [ 145.72415161]
 [ 182.27871704]
 [ 151.15805054]
 [ 145.28118896]
 [ 190.09979248]
 [ 147.51451111]
 [ 167.80621338]
 [ 171.2677002 ]
 [ 151.75204468]
 [ 168.67175293]
 [ 176.14996338]
 [ 159.2408905 ]
 [ 142.97511292]
 [ 191.81045532]]
20 Cost: 41.7982 
Prediction:
 [[ 146.07736206]
 [ 190.80929565]
 [ 180.08892822]
 [ 1