# Declear Tensors


## fixed tensors


In [1]:
import tensorflow as tf

In [2]:
# zero filled tensor
zero_tsr = tf.zeros([3,3])
zero_tsr

In [6]:
# one filled tensor
one_tsr = tf.ones([4,4])
print(one_tsr)

Tensor("ones_2:0", shape=(4, 4), dtype=float32)


In [8]:
# constant filled tensor
filled_tsr = tf.fill([2,3],23)
print(filled_tsr)

In [13]:
# create tensor out of an exsting constant
constant_tsr = tf.constant([[1,2,3],[4,5,6]])

print(constant_tsr)



## Tensors of similar shape



In [15]:
# initialize variables based on the shape of other tensors

zeros_similar = tf.zeros_like(constant_tsr)

ones_similar = tf.ones_like(constant_tsr)

print(zeros_similar)

print(ones_similar)

Tensor("zeros_like:0", shape=(2, 3), dtype=int32)
Tensor("ones_like:0", shape=(2, 3), dtype=int32)




## Sequence tensors



In [29]:
# specify tensors that contains defined intervals

# include the stop value
# linear_tsr = tf.linspace(start=0,num=3,stop=1)
linear_tsr = tf.linspace(-3.0, 3.0,32)

print(linear_tsr)

Tensor("LinSpace_10:0", shape=(32,), dtype=float32)


In [30]:
# tf.range()

integer_seq_tsr = tf.range(start=6,limit=15,delta=3)
print(integer_seq_tsr)

Tensor("range:0", shape=(3,), dtype=int32)


In [31]:
# random tensor

#include the minval but not the maxval 
# minval <= x <maxval

randomif_tsr = tf.random_uniform([4,4],minval=0,maxval=1)
print(randomif_tsr)

Tensor("random_uniform:0", shape=(4, 4), dtype=float32)


In [32]:
# normal distribution

randnorm_tsr = tf.random_normal([4,4],mean=0.0,stddev=1.0)
print(randnorm_tsr)

Tensor("random_normal:0", shape=(4, 4), dtype=float32)


In [33]:
# noramal random woth certain bound
# truncated_normal() function always 
# picks normal values within two standard deviations of the specified mean
# 在指定平均值的两个标准偏差内选择正常值

runnorm_tsr = tf.truncated_normal([4,4],mean=0.0,stddev=1.0)
print(runnorm_tsr)


Tensor("truncated_normal:0", shape=(4, 4), dtype=float32)


In [37]:
# random entry of arrays

# two functions: random_shuffle() and random_crop()
# shuffled_output = tf.random_shuffle(input_tensor)

shuffled_output = tf.random_shuffle(runnorm_tsr)
print(shuffled_output)

'''not working'''
#cropped_output = tf.random_crop(input_tensor,crop_size)
#cropped_output = tf.random_crop(runnorm_tsr,[1,2,3])
#print(cropped_output)

Tensor("RandomShuffle_3:0", shape=(4, 4), dtype=float32)


'not working'

In [ ]:
# random cropping an image of size (height,width,3)where there are three color spectrums
# to fix a dimension in the cropped_output, give the maximum size

cropped_image = tf.random_crop(my_image,[height/2,width/2,3])



# Using placeholders and Variables



## create a Variable by using the Variable() function take a tensor as an inputn and outpurs a variable

In [39]:


my_var = tf.Variable(tf.zeros(2,3))
sess = tf.Session()

initialize_op = tf.global_variables_initializer()

sess.run(initialize_op)


### placeholders are just holding the position for data to be fed into the graph placeholders get data froom a feed_dict argument in the session to put a placeholder in the graph we must perform at least one operation on the placeholder
 we initilize the graph ,declear x to be a placeholder and define y as the identity operation on x which just return x  then we create data to feed into the x placeholder and run the identify operation


In [42]:

import numpy as np
sess = tf.Session()

x = tf.placeholder(tf.float32,shape=[2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)
print(x_vals)
sess.run(y,feed_dict={x:x_vals})


[[ 0.48710287  0.47509735]
 [ 0.33764118  0.72502157]]


array([[ 0.48710287,  0.47509736],
       [ 0.33764118,  0.7250216 ]], dtype=float32)

### initialize variables by order

In [46]:


sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))
sess.run(first_var.initializer)
second_var = tf.Variable(tf.zeros_like(first_var))
sess.run(second_var.initializer)

In [47]:
print(first_var)
print(second_var)

Tensor("Variable_4/read:0", shape=(2, 3), dtype=float32)
Tensor("Variable_5/read:0", shape=(2, 3), dtype=float32)



# working with Matrices


In [1]:
import tensorflow as tf
sess = tf.Session()

## Create matrices

In [2]:
import numpy as np

identify_matrix = tf.diag([1.0,1.0,1.0])

A = tf.truncated_normal([2,3])

B = tf.fill([2,3],5.0)

C = tf.random_uniform([3,2])

D = tf.convert_to_tensor(np.array([[1.,2.,3.],[-3.,-4.,-5.],[-3.,-4.,-5.]]))


print(sess.run(identify_matrix))
print(sess.run(A))
print(sess.run(B))
print(sess.run(C))
print(sess.run(D))


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ -6.44778714e+37   3.15118732e-29   8.15233434e-34]
 [  6.75814822e+16   1.39296411e-33   6.78552606e+16]]
[[ 5.  5.  5.]
 [ 5.  5.  5.]]
[[ -4.38748375e+37   2.91891591e-39]
 [  3.26205633e-33   6.75726861e+16]
 [  3.26262571e-33   6.75803827e+16]]
[[ 1.  2.  3.]
 [-3. -4. -5.]
 [-3. -4. -5.]]


## transpose


In [3]:
print(sess.run(C))

print(sess.run(tf.transpose(C)))

[[ -6.44778714e+37   2.06473298e-24]
 [  5.57297904e-33   6.78464645e+16]
 [  4.80260780e-33   6.75660890e+16]]
[[ -6.58070994e+37   2.06514950e-24   1.39277309e-33]
 [  6.78376684e+16   1.20018028e-33   6.75572929e+16]]


## determinant

In [4]:
print(sess.run(D))

print(sess.run(tf.matrix_determinant(D)))

[[ 1.  2.  3.]
 [-3. -4. -5.]
 [-3. -4. -5.]]
0.0


In [5]:
print(sess.run(A+B))

print(sess.run(A-A))

print(sess.run(B))
print(sess.run(identify_matrix))

#print(sess.run(tf.matmul(B,identify_matrix)))

[[ -6.58070994e+37   2.06514950e-24   5.57259701e-33]
 [  6.78376684e+16   4.80222577e-33   6.75572929e+16]]
[[ -4.38748375e+37   2.91891591e-39   1.00758692e-33]
 [  6.78365689e+16   1.00763523e-33   6.75627905e+16]]
[[ 5.  5.  5.]
 [ 5.  5.  5.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Cholesky decomposition 分解

In [7]:
print(sess.run(tf.cholesky(identify_matrix)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Eigenvalues and eigenvectors 
特征值和特征向量

In [9]:
print(sess.run(tf.self_adjoint_eig(D)))

(array([-10.14150955,  -0.48757004,   2.62907959]), array([[ 0.35545039,  0.07070271, -0.93201724],
       [ 0.62581312,  0.72264855,  0.29349106],
       [ 0.69427153, -0.68759014,  0.21261903]]))


# Declearing Opeartions

In [1]:
import tensorflow as tf
sess = tf.Session()

In [2]:
print(sess.run(tf.div(3,4)))

0


In [10]:
print(sess.run(tf.truediv(3.0,4.0)))
print(sess.run(tf.truediv(3,4)))

0.75
-1.00680577424e+308


In [11]:
print(sess.run(tf.floordiv(3,4)))
print(sess.run(tf.floordiv(3.0,4.0)))


0
0.0


In [12]:
print(sess.run(tf.mod(22.0, 5.0)))

2.0


In [13]:
print(sess.run(tf.cross([1., 0., 0.], [0., 1., 0.])))

[ 0.  0.  1.]


In [14]:
print(sess.run(tf.div(tf.sin(3.1416/4.), tf.cos(3.1416/4.))))

1.0


In [18]:
## sub substrct

def custom_polynomial(value):
    return(tf.subtract(3 * tf.square(value), value) + 10)
print(sess.run(custom_polynomial(11)))

362


# implement activation function

In [19]:
import tensorflow as tf
sess = tf.Session()

## relu function

max(0,x)

In [20]:
print(sess.run(tf.nn.relu([-3,3,10])))

[ 0  3 10]


## relu6 function
### min(max(0,x),6)


This is a version of the hard-sigmoid function and is
computationally faster, and does not suffer from vanishing
(infinitesimally near zero) or exploding values.
这是一个硬Sigmoid函数的版本，计算速度更快，并且不会消失（无限大近零）或爆炸值。

In [23]:
print(sess.run(tf.nn.relu6([-3,3,10])))

[0 3 6]


## sigmoid function

The sigmoid function is the most common continuous and smooth activation function. 
It is also called a logistic function and has the form
#### 1/(1+exp(-x)). 
#### The sigmoid is not often used because of the tendencyto zero-out the back propagation terms during training
由于在训练期间零背反向传播术语的倾向，S型并不经常被使用。

In [22]:
print(sess.run(tf.nn.sigmoid([-1., 0., 1.])))

[ 0.26894143  0.5         0.7310586 ]


## hyper tangent function

it has a range between -1 and 1 . 
The function has the form of the ratio of the hyperbolic sine over the hyperbolic cosine. But another way to write this is 
#### ((exp(x)-exp(- x))/(exp(x)+exp(-x)).

In [24]:
print(sess.run(tf.nn.tanh([-1., 0., 1.])))

[-0.76159418  0.          0.76159418]


### softsign
x/(abs(x) + 1)
The softsign function is supposed to be a continuous approximation to the sign function.

In [26]:
print(sess.run(tf.nn.softsign([-1., 0., 1.])))

[-0.5  0.   0.5]


### softplus
smooth version of the ReLU function. 
The form of this function is 
###### log(exp(x) + 1)

In [27]:
print(sess.run(tf.nn.softplus([-1., 0., 1.])))

[ 0.31326166  0.69314718  1.31326163]


###### The softplus goes to infinity as the input increases whereas the softsign goes to 1. 
######  As the input gets smaller, however, the softplus approaches zero and the softsign goes to -1.

## Exponential Linear Unit (ELU) 
very similar to the softplus function except that the bottom asymptote is -1 instead of 0 . 
##### (exp(x)+1) if x < 0        else x.

In [28]:
print(sess.run(tf.nn.elu([-1., 0., 1.])))

[-0.63212055  0.          1.        ]
